//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryEDMConsoleApp
{
    using System;
    using System.Collections.Generic;

    public partial class Car
    {
        public int CarID { get; set; }
        public string Make { get; set; }
        public string Color { get; set; }

        public string CarNickName { get => _CarNickname; set {
                _CarNickname = value;
                OnCarNicknameChanging(value);
                OnCarNicknameChanged();
         
            } }

        public override string ToString()
        {
            return string.Format("{0} is  a {1} {2} with ID {3}.", this.CarNickName ?? "**No Name**", this.Color, this.Make, this.CarID);
        }

        partial void OnCarNicknameChanging(global::System.String value)
        {
            Console.WriteLine("\t -> Changing name to:{0}", value);
        }
        partial void OnCarNicknameChanged()
        {
            Console.WriteLine("\t-> Name of car has been changed!");
        }

        private global::System.String _CarNickname;
        partial void OnCarNicknameChanging(global::System.String value);
        partial void OnCarNicknameChanged();
    }
}
